jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build

test:
  runs-on: macOS-10.15
  steps:
    - uses: actions/checkout@v2
    - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger=trx

name: ci-pipeline

on: push
# test:
#   runs-on: ubuntu-20.04
#   steps:
#     - uses: actions/checkout@v2
#     - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=./test_coverage/ -l trx -r ./test_result/
#

# test: xunit + CoverletOutput
# analyze: sonarcloud = static code analysis
# package: docker image

